// List of hardcoded Ticket along with their details.

var projectData = {
    projectList: [{
        Id: 1,
        ProjectName: 'ESPL - MSPlus CoE',
        ProjectType: 'Internal',
        DeliveryUnit: 'Microsoft',
        ProjectCategory: 'Delv - CoE (MSPlus)',
        ClientName: 'Eternus Solutions Pvt Ltd',
        ProjectStartDate: '01-05-2014',
        ProjectEndDate: '30-11-2015	',
        ProjectManager: 'Aradhana Chindhade	',
        AccountManager: 'Kunal Kirankumar Adhikari',
        DeliveryManager: 'Kunal Kirankumar Adhikari',
        BillType:'Billable',
        ProjectSummary: 'Project Summary',
        DeliveryModel:'ODC Model',
        PriceType:'Fixed',
        TeamSize: 10,
        IsActive: true,
        IsGlobal: true
    },
    {
        Id: 2,
       ProjectName: 'ESPL - Practice Management - MSPlus',
        ProjectType: 'Internal',
        DeliveryUnit: 'Microsoft',
        ProjectCategory: 'Delv - CoE (MSPlus)',
        ClientName: 'Eternus Solutions Pvt Ltd',
        ProjectStartDate: '01-05-2014',
        ProjectEndDate: '30-11-2015	',
        ProjectManager: 'Kunal Kirankumar Adhikari',
        AccountManager: 'Kunal Kirankumar Adhikari',
        DeliveryManager: 'Kunal Kirankumar Adhikari',
        BillType:'Billable',
        ProjectSummary: 'Project Summary',
        DeliveryModel:'ODC Model',
        PriceType:'Fixed',
        TeamSize: 10,
        IsActive: true,
        IsGlobal: true
    }, {
        Id: 3,
        ProjectName: 'Go Nimbly',
        ProjectType: 'Internal',
        DeliveryUnit: 'Microsoft',
        ProjectCategory: 'Delv - CoE (MSPlus)',
        ClientName: 'Go Nimbly',
        ProjectStartDate: '01-05-2014',
        ProjectEndDate: '30-11-2015	',
        ProjectManager: 'Sagar Shelar',
        AccountManager: 'Kunal Kirankumar Adhikari',
        DeliveryManager: 'Kunal Kirankumar Adhikari',
        BillType:'Billable',
        ProjectSummary: 'Project Summary',
        DeliveryModel:'ODC Model',
        PriceType:'Fixed',
        TeamSize: 10,
        IsActive: true,
        IsGlobal: true
    }, {
        Id: 4,
        ProjectName: 'Jenzabar - Web Corporate',
        ProjectType: 'Internal',
        DeliveryUnit: 'Microsoft',
        ProjectCategory: 'Delv - CoE (MSPlus)',
        ClientName: 'Jenzabar',
        ProjectStartDate: '01-05-2014',
        ProjectEndDate: '30-11-2015	',
        ProjectManager: 'Prasad Udupi	',
        AccountManager: 'Kunal Kirankumar Adhikari',
        DeliveryManager: 'Kunal Kirankumar Adhikari',
        BillType:'Billable',
        ProjectSummary: 'Project Summary',
        DeliveryModel:'ODC Model',
        PriceType:'Fixed',
        TeamSize: 10,
        IsActive: true,
        IsGlobal: true
    }, {
        Id: 5,
        ProjectName: 'Synergy Code',
        ProjectType: 'Internal',
        DeliveryUnit: 'Microsoft',
        ProjectCategory: 'Delv - CoE (MSPlus)',
        ClientName: 'Eternus Solutions Pvt Ltd',
        ProjectStartDate: '01-05-2014',
        ProjectEndDate: '30-11-2015	',
        ProjectManager: 'Sagar Shelar	',
        AccountManager: 'Kunal Kirankumar Adhikari',
        DeliveryManager: 'Kunal Kirankumar Adhikari',
        BillType:'Billable',
        ProjectSummary: 'Project Summary',
        DeliveryModel:'ODC Model',
        PriceType:'Fixed',
        TeamSize: 10,
        IsActive: true,
        IsGlobal: true
    }],
    ids: 7
};

module.exports = projectData;